### ISSUE TITLE
Code not working with newest shinyIncubator revision

### ISSUE THREAD

**Issue by doenertier83** [rstudio/shiny-examples#11]
Please modify the example so that it is working with the newest shiny & shinyIncubator revision.

**Comment by alevashov** [comment]
Same there, getting `Error in tag("div", list(...)) : could not find function "progressInit"`

**Comment by jcheng5** [comment]
@yihui or @garrettgman, can one of you please modify any progress examples to not call progressInit (and not use shinyIncubator if they're only doing so for the progress API, which is now only in Shiny)?

Thanks...

**Comment by wch** [comment]
I already removed that outdated example in 91d03fd0d9328552ddf09300d966ac5502505cb0. It's also gone from the gallery page.

**Comment by wch** [comment]
Oh oops, it's still present in the wordcloud example, but I can fix that as well.

**Comment by wch** [comment]
OK, the wordcloud example is fixed now, and the gallery app has been re-deployed.

**Comment by jcheng5** [comment]
Thanks @wch!
