### ISSUE TITLE
RSQLite.extfuns not on cran anymore?

### ISSUE THREAD

**Issue by bernardcornet** [rstudio/shiny-examples#12]
Hello!
I'm only starting out, but shiny and the example gallery looks amazing. 
However, seems like RSQLite.extfuns is not on cran anymore.
http://cran.r-project.org/web/packages/RSQLite.extfuns/index.html

Maybe the tutorial should be updated with something like this?
download.file("http://cran.r-project.org/src/contrib/Archive/RSQLite.extfuns/RSQLite.extfuns_0.0.1.tar.gz", 
  "boot")
install.packages("boot", repos = NULL, type = "source")

**Comment by lcmercado** [comment]
Thanks @bernardcornet Indeed, for some reason the RSQLite package doesn't fully support the RSQLite.extfuns package. I used your workaround and now the graph is available, whereas it was missing before I did that.
