### ISSUE TITLE
No progressInit()?

### ISSUE THREAD

**Issue by nhpackard** [rstudio/shiny-examples#14]
I get:
ERROR: could not find function "progressInit"
maybe this is version skew with current shinyIncubator?

**Comment by jcheng5** [comment]
Yes, the progress examples are out of date now. They don't need the progressInit() call and in fact don't need shinyIncubator, as the progress functionality is now part of the shiny package itself.

@wch @yihui @garrettgman Does one of you mind updating the examples? I would if I wasn't leaving for vacation in the morning :)

**Comment by wch** [comment]
One of the progress bar examples is up to date, but the other one uses shinyIncubator. I'll just remove the second one.

**Comment by wch** [comment]
I've removed the example in 91d03fd0d9328552ddf09300d966ac5502505cb0. I also updated the gallery to reflect this.

**Comment by garrettgman** [comment]
Thanks, Winston!

**Comment by zx8754** [comment]
Related post on SO:

https://stackoverflow.com/questions/35037230/change-style-and-position-of-the-message-box-generated-by-withprogress
