### ISSUE TITLE
htmltools package error in Shiny Server Pro gallery examples

### ISSUE THREAD

**Issue by thercast** [rstudio/shiny-examples#15]
Hi, I was showing your examples of Shiny server Pro authentication from the gallery to a colleague and when I logged in as one of the users, the app could not render and displayed a message of `ERROR: there is no package called htmltools`.  For reference the apps are the following:
- http://shiny.rstudio.com/gallery/authentication-and-database.html 
- http://shiny.rstudio.com/gallery/personalized-ui.html

**Comment by jcheng5** [comment]
That's strange, htmltools is a required dependency for Shiny--not sure how
your server could have installed Shiny without it. Anyway, installing it in
whatever library shiny is in should solve it.

**Comment by thercast** [comment]
Hi Joe, sorry I was not clear on the error.  This error is occurring when I access the gallery examples themselves via the Shiny gallery apps page, not when I deploy it internally.  Here's a screenshot in case it helps:

![image](https://cloud.githubusercontent.com/assets/1043111/6250948/01777902-b75f-11e4-8228-68bdd2a9ede7.png)

**Comment by jcheng5** [comment]
Oh! Thanks for the heads up! We're investigating now.

**Comment by mine-cetinkaya-rundel** [comment]
@thercast I believe these apps should be running without issues, please let us know if you run into a similar problem
