### ISSUE TITLE
Broken link in the client-data-and-query-string example

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/shiny-examples#18]
On this page:

https://gallery.shinyapps.io/032-client-data-and-query-string/

This link:
http://gallery.shinyapps.io/client-data-and-query-string?a=xxx&b=yyy#zzz

should be changed to this:
https://gallery.shinyapps.io/032-client-data-and-query-string/?a=xxx&b=yyy#zzz

**Comment by yihui** [comment]
Good catch. Thanks! Fixed and will re-deploy the app soon.

**Comment by fereshtehRS** [comment]
Thanks!
