### ISSUE TITLE
RSQLite

### ISSUE THREAD

**Issue by jiyelee14** [rstudio/shiny-examples#182]
Hello,
I have a problem.

My code and error: 

library(shiny)
library(shinydashboard)
library(ggplot2)
library(DT)
library(plotly)
library(ggvis)
library(dplyr)
if (FALSE) {
  library(RSQLite)
  library(dbplyr)
}

axis_vars <- c(
  "Tomato Meter" = "Meter",
  "Numeric Rating" = "Rating",
  "Number of reviews" = "Reviews",
  "Dollars at box office" = "BoxOffice",
  "Year" = "Year",
  "Length (minutes)" = "Runtime"
)

db <- src_sqlite("movies.db")

Error in loadNamespace(name) : there is no package called ‘RSQLite’

I installed ‘RSQLite’ and restart R. But this didn't solve the problem.

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
