### ISSUE TITLE
Few more examples to renderDataTable

### ISSUE THREAD

**Issue by jangorecki** [rstudio/shiny-examples#2]
Hi,
I found those examples very useful, there quite a few shiny+dataTables options tutorials over the web.
If possible I would propose to include some more examples:
- Numeric formatting like: thousands separators, decimal separators, decimal precision.
- Date formatting
- Text encoding - I still cannot render polish country specific characters, I've check shiny::renderTable return value, it shows them well, but on the webpage it is not. I believe it is dataTables js side encoding issue. Setting options(encoding = "UTF-8") doesn't help.
Regards,
Jan

**Comment by jangorecki** [comment]
The best would be to have Date format the same as in the R `as.character(Sys.Date(),"%Y%m")`, of course conversion to character is not to solution as it would lose for example the sorting capability. Instead of keeping two copies, one integer (order), another character (labels) this might be done by active binding of labels to order.

**Comment by yihui** [comment]
Got you. You can store the dates as character strings, and format them using JavaScript (http://stackoverflow.com/q/1056728/559676). See section 2.5.2: http://rstudio.github.io/DT/ I can also consider a wrapper function just like other formatting functions in DT (such as `formatCurrency()`).

**Comment by jangorecki** [comment]
Ok, thanks for the links. Wrapper function might be helpful. Closing issue.
