### ISSUE TITLE
brushedPoints() and coord_flip() fails

### ISSUE THREAD

**Issue by tvedebrink** [rstudio/shiny-examples#24]
When combining coord_flip() with brushedPoints() it seems to fail?
If taking the example on https://gallery.shinyapps.io/095-plot-interaction-advanced/ with "plot type = ggplot2" and setting "scale type = coord_flip()" the output (selected rows when brushing) is empty. Any clues?

**Comment by yihui** [comment]
Thanks for the report. I can reproduce it. Cc @wch

**Comment by mine-cetinkaya-rundel** [comment]
This issue seems to have been resolved @tvedebrink, I'm able to see the selected rows when brushing with "plot type = ggplot2" and "scale type = coord_flip()".
