### ISSUE TITLE
enhancement: add transition-delay to modals - Example 107-Events 

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny-examples#25]
@yihui  Great example on how to use modals (currently in the shiny-events branch).

It would be great if you could add in the example transition-delay: this would be very useful for the `'busyModal'`: you may want to ignore all delays below say a 3s threshold...

**Comment by yihui** [comment]
Sorry I don't quite get it. What is transition-delay?

**Comment by smartinsightsfromdata** [comment]
@yihui I met @jcheng5 at the EARL conference in London and I asked how to introduce a delay in the modal notification (I had seen your example).  

I managed to integrate your code successfully in my app (thanks again!), but I am most interest in managing the shiny-busy states.  In the current implementation the modal comes up immediately for any delay on the system, short or long.  I discussed with Joe how to introduce a threshold of some kind, say 3s.

He suggested to look into the `css` feature `transition-delay`. 

I tried to use it but I got nowhere. Thanks in advance for any help.

**Comment by yihui** [comment]
It seems to work for me. I tried to add `style = 'transition-delay: 2s;'` to the `busyModal` div, and the modal no longer shows up immediately.

```r
  div(
    id = 'busyModal', class = 'modal fade', role = 'dialog',
    style = 'transition-delay: 2s;',
    div(
      class = 'modal-dialog modal-sm',
      div(
        class = 'modal-content',
        div(class = 'modal-header', h4(class = 'modal-title', 'Shiny is busy!')),
        div(class = 'modal-body', p(paste(
          'This dialog box will disappear',
          'automatically after shiny is idle.'
        )))
      )
    )
  )
```

**Comment by smartinsightsfromdata** [comment]
great stuff! thanks
