### ISSUE TITLE
Links in Readme

### ISSUE THREAD

**Issue by demidovakatya** [rstudio/shiny-examples#28]
In the first paragraph of `README.md`:

> This is a collection of Shiny examples. You can see them in action on
**https://demo.shinyapps.io/example-name** where `example-name` is the directory
name of an example here, e.g. **https://**demo.shinyapps.io/001-hello

* 1st link – 404 bad request
* https://demo.shinyapps.io/ – 400 bad request
* 2nd link – redirect to `https`

Absence of some index page for `demo.shinyapps.io` was a little bit misleading.

**Comment by yihui** [comment]
Just updated README. Thanks!
