### ISSUE TITLE
for 016-knitr-pdf, input$x in code chunks?

### ISSUE THREAD

**Issue by ndimhypervol** [rstudio/shiny-examples#29]
Great example for making pdf reports with knitr in a shiny app, but I was wondering if you could insert input$x into a code chunk instead of just inline code. I'd like to display the result of a user input as a parameter to a function call, and display this in a code chunk. I made a stackexchange issue about this [here](http://stackoverflow.com/questions/34375756/rmarkdown-shiny-user-input-in-chunk). Is there any way to do this? Thanks.

**Comment by yihui** [comment]
I have given a brief answer on SO. Sorry I don't have time to write a complete answer.
