### ISSUE TITLE
Customization with Datatables

### ISSUE THREAD

**Issue by jjcole415** [rstudio/shiny-examples#36]
I have been trying to play around with customizing datatables for a shiny app I am working on, and have run across several posts, but none really solve the problems that I am having.  

See for example:
https://github.com/rstudio/shiny-examples/issues/9
http://stackoverflow.com/questions/29786286/how-to-use-row-grouping-for-datatables-in-shiny

I have a table of data on several different stock managers, which lists the stocks they hold, number of shares, and current market value (among other things). Ultimately, I want to transform that data into a table which will display the aggregate totals across these managers, but when clicked these rows will reveal x number of child rows showing which managers hold these stocks and the specific values. 

Here is a snapshot of the data from Rstudio:

![image](https://cloud.githubusercontent.com/assets/10905001/13717950/20879018-e79a-11e5-87bc-ae58cb5c162c.png)

I have been playing around with the row.grouping feature, but can't  seem to get this to work even at the most basic level. In part I think the problem is caused by the quotation marks. This code below being the first part of the example from the datatable.net site. 

https://datatables.net/examples/advanced_init/row_grouping.html 

```
datatable(combinedData, options = list(
  drawCallback = JS(
    "function(settings){",
    "var api = this.api();",
    "var rows = api.rows({page:'current'}).nodes();",
    "var last = null;",

    "api.column(2).data.each(function(group,i){",
    "if (last !== group){",
      "$(rows).eq(i).before(",
      '<tr class=\"group\"><td colspan=\"5\">'+group+'</td></tr>'"
          ");",
        "last = group;",
        "}",
      "});",
      "}", sep =""))))
```

Is what I am doing even possible with datatables through R and shiny.  I have seen others posting their codes in jsfiddle, but even these other examples cannot be sorted by the group values, which is something I would like to ultimately do. 

http://jsfiddle.net/X5LB9/1/
http://jsfiddle.net/968Pn/6/

Another thought would be to aggregate what I have and call on another table's data to populate child rows, but again, I do not see examples or documentation for this.  Any assistance would be much appreciated.

**Comment by mauritzvdworm** [comment]
Any progress on this?  I want to do something similar.

**Comment by jjcole415** [comment]
Sort of.  I have come up with two workarounds. 

1. The first uses package shinyBS to create a new table that displays as a popup when a stock is selected in the datatable. This is okay, but there are some issues with that fix.  First, for some reason, the single select option will not work, and second, with multiple selections, the results are often a bit screwy and unpredictable.  This means that the user has to be sure to deselect the row before trying to view another selected rows results.    

2. I struggled to write my own script that would allow some drill down capability.  However, I could not get the results I truly wanted which was a true child rows, accordion-like drill down view.  Instead I settled for a single child row that listed a few data points.  

```
  datatable(
    cbind(' ' = '&oplus;', df), escape = 1, extensions = 'TableTools',
    caption = htmltools::tags$caption(
      style = 'caption-side: top; text-align: center; color: black ;',
      htmltools::h3("Top Winners and Losers")
    ),
    options = list(lengthMenu = c(10,50,100,nrow(df)), order = list(5, 'desc'),tableTools = list(sSwfPath = copySWF('www')),
                   columnDefs = list(
                     list(visible = FALSE, targets = c(0, 10)),
                     list(orderable = FALSE, className = 'details-control', targets = 1)
                   )
    ),
    callback = JS("
                table.column(1).nodes().to$().css({cursor: 'pointer'});
                var format = function(d) {
                return '<div style=\"background-color:#eee; padding: .5em;\">' +
                d[10] +  '</div>';
                };
                table.on('click', 'td.details-control', function() {
                var td = $(this), row = table.row(td.closest('tr'));
                if (row.child.isShown()) {
                row.child.hide();
                td.html('&oplus;');
                } else {
                row.child(format(row.data())).show();
                td.html('&CircleMinus;');
                }
                });"
    ))%>%
    formatPercentage(c(5:9),2)
  
})

```

It has been a while since I wrote this and I am not sure I understand javascript well enough to explain it succinctly but it did work.  Here is a screen shot of how it looks:

![image](https://cloud.githubusercontent.com/assets/10905001/20614798/a4a37b7e-b287-11e6-8cf3-f7cce292416c.png)

I plan to revise my code in the coming months as we change some underlying data systems.  I will be happy to share any new insight then.  If you have any further ideas, thoughts, breakthroughs, please let me know.  

Jon

**Comment by mauritzvdworm** [comment]
@jjcole415 thanks for the reply.  I've been using similar code to that you show above, but it doesn't give exactly what I need.  It is easy enough to get the desired effect with excel, but I am clueless on how to achieve it using datatable.  I'll let you know if I manage to get a good result.

**Comment by mahakgulati** [comment]
I have done the same thing. Works fine in Rshiny also but not working on Rstudio server. Can you help me find the problem.
Thanks!
