### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by nikolai-b** [rstudio/shiny-examples#40]
I am trying to work out what browser versions my shiny app works on.
Some of the apps in this repo have supported browser tables but 063-superzip-example does not.
I've just tried with IE8 on Win7 https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ (in Vagrant as I'm on Linux so IE version 8.0.7601.17514) and it fails:

```
  'undefined' is null or not an object  pinit_main.js?0.22231112147439086, line 1 character 24032
  Expected identifier  datatables.js, line 76 character 14
LOG: Fri Jul 29 05:16:07 PDT 2016: Connection opened. https://gallery.shinyapps.io/063-superzip-example/
  Invalid argument.  leaflet.js, line 7 character 2344
LOG: Fri Jul 29 05:19:01 PDT 2016: Connection closed. Info: {"type":"close","code":1006,"reason":"Server lost session","wasClean":false}
```

Similar with 086-bus-dashboard 

```
LOG: Fri Jul 29 05:30:10 PDT 2016: Connection opened. https://gallery.shinyapps.io/086-bus-dashboard/
  Invalid argument.  leaflet.js, line 7 character 2344
```

Is this a know issue?  Is there some compatibility information I can find about?  Leaflet itself works fine (as in the maps on http://leafletjs.com/ load) and supports IE 7-11.

Sorry if this is the wrong place to report this.

**Comment by wch** [comment]
We used to support IE8 but haven't been doing so since Microsoft ended support for IE8.
