### ISSUE TITLE
Example 107-events: "Shiny is busy" when it is idle

### ISSUE THREAD

**Issue by tiagochst** [rstudio/shiny-examples#51]
Hi,

I have some heavy plots that takes more than 1 minute to be rendered.
I was trying to use a busy state to show a message like "working in progress". 
However, I have the same problem that happens in the
[example 107-events](https://gallery.shinyapps.io/107-events/), the box "Shiny is busy" suddenly shows and hides when it was supposed to be idle.

Is there a solution ?

Thanks.

**Comment by wch** [comment]
That's actually the intended behavior. This is what triggers it every 10 seconds:

```R
  observe({
    invalidateLater(10000, session)
    message('Shiny will be busy for 1 second')
    Sys.sleep(1)
  })
```

I agree that it's confusing though, so I'll see about changing it.

**Comment by wch** [comment]
I changed it so you need to push a button to trigger the busy state.

**Comment by tiagochst** [comment]
Thank you very much! Also,  I was able to add the "rendering in progress" , but using the shiny:recalculating and shiny:recalculated events.
