### ISSUE TITLE
The selectizeinput in 021-selectize-plot/ is not working

### ISSUE THREAD

**Issue by happyshows** [rstudio/shiny-examples#6]
Hi,

I have tried https://demo.shinyapps.io/021-selectize-plot/ and also download & run locally, the selectizeInput does not seem to function.
Can you guys check to see what's happening (Honestly, I didn't understand very well what it's supposed to do either)

**Comment by yihui** [comment]
It is supposed to respond when you type in the selectize input. It is a fairly advanced example based on selectize.js. See a screenshot below:

![s](https://cloud.githubusercontent.com/assets/163582/6956919/40c727c0-d8ba-11e4-8097-3761bed9635e.png)
