### ISSUE TITLE
059-reactive-poll-and-file-reader has a typo

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny-examples#62]
> This side uses a reactiveFileReader, which is monitoring the log file for changes every 0.5 seconds.

Should be:

This side uses a reactiveFileReader, which is monitoring the log file for changes every **1 second**.

**Comment by wch** [comment]
I think it's correct: https://github.com/rstudio/shiny-examples/blob/master/059-reactive-poll-and-file-reader/server.R#L36-L38

However, the log writer runs once per second.

**Comment by bborgesr** [comment]
You're right, sorry, skimmed too fast through that one. It does seem a little confusing though... Why not make it so that both monitoring and writing be synced? In either case, it's not a bug, so I'll close this.
