### ISSUE TITLE
renderUI not working in absolutePanel of tabPanel

### ISSUE THREAD

**Issue by sameer-sinha** [rstudio/shiny-examples#64]
I have been referring **063-superzip-example** to create something similar. I have been trying to use uiOutput and renderUI to create a dynamic selectInput box, whose values will be based on the unique values of a dataframe column. I have tried putting this selectInput inside the absolutePanel, but it won't generate any ui. The same piece of code works flawlessly with other layouts, such as tabsetPanel etc.

Is there any kind of limitation with absolutePanel or am I missing something ?

**Comment by wch** [comment]
Can you provide a minimal reproducible example?

**Comment by sameer-sinha** [comment]
I had posted the question on stackoverflow. Please check this [link](http://stackoverflow.com/questions/43740730/renderui-not-working-in-absolutepanel-of-tabpanel)

**Comment by wch** [comment]
I mean an entire app for a reproducible example. (It makes it much easier for others to help if they don't have to create a working app themselves.)

**Comment by sameer-sinha** [comment]
I created a small app and it was working correctly. Checked my original code and it seems to be working correctly now. My bad. Closing this issue.
