### ISSUE TITLE
404 for message-handler.js

### ISSUE THREAD

**Issue by geotheory** [rstudio/shiny-examples#65]
Hi. I've objectivised your functions as `server` and `ui` respectively and called them with `shinyApp(ui, server, options = list(launch.browser=T))`.  But on client side the browser isn't picking up on `message-handler.js` (which yes is in subfolder `www`).  Chrome console reports:

    message-handler.js Failed to load resource: the server responded with a status of 404 (Not Found)

My app is served to `http://127.0.0.1:6416/`, and runs fine except for lack of the alert message.  `http://127.0.0.1:6416/www` and `http://127.0.0.1:6416/www/message-handler.js` and `http://127.0.0.1:6416/message-handler.js` all return `Not Found`.

Am I missing something?

**Comment by jcheng5** [comment]
Shiny only uses the www folder mechanism if it knows the base directory of your Shiny app. If you make an app.R style app and run it by sourcing the file, Shiny doesn't know the path to the file. However if you do `runApp("path-to-appdir")` then it should work. Let us know if not.

**Comment by helgasoft** [comment]
geotheory  is correct, subfolders are inacessible, only the working directory is visible.
Example:   tags$img(src="./www/my.jpg")   generates 404 not found, same with "src="www/my.jpg"
 tags$img(src="my.jpg")  works fine
