### ISSUE TITLE
Super Zip - dateInput on Safari and Chrome

### ISSUE THREAD

**Issue by carlocav** [rstudio/shiny-examples#69]
In the Super Zip example, if I add a dateInput in the absolutePanel, at least in Safari and Chrome the popup window opens at the right of the input instead of below and it is impossible to choose a date without moving to the left the entire absolutePanel.
<img width="487" alt="screen" src="https://user-images.githubusercontent.com/28147072/31074105-54ea7244-a76f-11e7-94a3-23dabbc906cf.png">

**Comment by wch** [comment]
Can you file this issue at https://github.com/rstudio/shiny/issues, and also include a simple reproducible example? Thanks!
