### ISSUE TITLE
026-shiny-inline is empty

### ISSUE THREAD

**Issue by Stan125** [rstudio/shiny-examples#70]
This example does not work; ui/server are missing. It is not displayed on the website either:
http://shiny.rstudio.com/gallery/inline-output.html

**Comment by yihui** [comment]
This app is a Shiny R Markdown document. It suffices to have an index.Rmd.

That said, it seems this app should be redeployed. Cc @wch

**Comment by mine-cetinkaya-rundel** [comment]
The app is back up and running now: http://shiny.rstudio.com/gallery/inline-output.html

Thanks for reporting @Stan125!

**Comment by Stan125** [comment]
@yihui Ah. I get it :-)
@mine-cetinkaya-rundel No problem!
