### ISSUE TITLE
063-superzip example: Map is hiding the absolute panel

### ISSUE THREAD

**Issue by JoFAM** [rstudio/shiny-examples#85]
Apparently something changed in shiny and/or leaflet. The absolute panel is not visible any longer as it is hidden now behind the map.

**Comment by schloerke** [comment]
@JoFAM This is fixed in https://github.com/rstudio/leaflet/pull/537

Please download the latest from master.  

```r
devtools::install_github("rstudio/leaflet")
```

**Comment by JoFAM** [comment]
@schloerke I have no access to the rstudio servers. It's not fixed in the gallery.

http://shiny.rstudio.com/gallery/superzip-example.html

**Comment by schloerke** [comment]
@JoFAM 

Oh! Which browser are you using? Which operating system do you have?

Thank you!

**Comment by JoFAM** [comment]
@schloerke Firefox on Windows 10. I just checked, and the problem seems solved. Probably I got caught in a cache or changes were still propagated through the systems.

Kind regards
