### ISSUE TITLE
How about a example of data tables child row?

### ISSUE THREAD

**Issue by CptanPanic** [rstudio/shiny-examples#9]
Something like https://datatables.net/examples/api/row_details.html

http://stackoverflow.com/questions/23635552/shiny-datatable-with-child-rows-using-ajax

**Comment by yihui** [comment]
You may try the new DT package: http://rstudio.github.io/DT/

Here is one example: http://rstudio.github.io/DT/002-rowdetails.html

**Comment by aditya-kothari** [comment]
In the example below, same number of child rows (in this case 1 row) are present for every parent row.

http://rstudio.github.io/DT/002-rowdetails.html

Is there a way to add dynamic child rows to the parent row from another data frame? in R? meaning one parent row can have 6 (lets day) child rows based on data in parent row and another parent row can have 2 or may be no rows based on data in their respective parent rows.

Thanks for your time!

**Comment by davlee1972** [comment]
I just finished an example trying to do the same thing sort of..

Grouped mpg, cyl, disp together. Shows all matching cars under each group. There should be some way to iterate through nested levels of columns containing data.tables, but the javascript necessary to do this is beyond me..

library(DT)
library(data.table)

# Transform dataframe to data.table and turn the dataframe rowname into a data.table column called model
mtcars_dt = data.table(mtcars)
mtcars_dt[["model"]] = rownames(mtcars)
setcolorder(mtcars_dt,c(
  which(colnames(mtcars_dt) %in% c("mpg","cyl","disp","model")),
  which(!colnames(mtcars_dt) %in% c("mpg","cyl","disp","model"))
))

# Turn data table into a nested data.table by mpg, cyln disp
mtcars_dt <- mtcars_dt[, list(cars=list(.SD)), by = list(mpg,cyl,disp)]

#configure datatable. Hide row number and cars columns [0,5] and enable details control on plus sign column[1]
#turn rows into child rows and remove from parent

datatable(
  cbind(' ' = '&oplus;', mtcars_dt), escape = -2,
  options = list(
    columnDefs = list(
      list(visible = FALSE, targets = c(0,5)),
      list(orderable = FALSE, className = 'details-control', targets = 1)
    )
  ),
  callback = JS("
  table.column(1).nodes().to$().css({cursor: 'pointer'});

  // Format cars object into another table
  var format = function(d) {
    if(d != null){
      var result = '<table class=\"table table-striped\">' + 
      '<thead><tr><th>model</th><th>hp</th><th>drat</th><th>wt</th><th>qsec</th><th>vs</th><th>am</th><th>gear</th><th>carb</th></tr></thead>'
      for (i = 0; i < + d[5]['model'].length; i++) {
        result += '<tr>' +
        '<td>' + d[5]['model'][i] + '</td>' +
        '<td>' + d[5]['hp'][i] + '</td>' +
        '<td>' + d[5]['drat'][i] + '</td>' +
        '<td>' + d[5]['wt'][i] + '</td>' +
        '<td>' + d[5]['qsec'][i] + '</td>' +
        '<td>' + d[5]['vs'][i] + '</td>' +
        '<td>' + d[5]['am'][i] + '</td>' +
        '<td>' + d[5]['gear'][i] + '</td>' +
        '<td>' + d[5]['carb'][i] + '</td>' +
        '</tr>'
      }
      return result + '</table>';
    }else{
      return '';
    }
  }

  table.on('click', 'td.details-control', function() {
    var td = $(this), row = table.row(td.closest('tr'));
    if (row.child.isShown()) {
      row.child.hide();
      td.html('&oplus;');
    } else {
      row.child(format(row.data())).show();
      td.html('&CircleMinus;');
    }
  });"
  )
)

**Comment by davlee1972** [comment]
I just finished an example trying to do the same thing sort of..

Grouped mpg, cyl, disp together. Shows all matching cars under each group. There should be some way to iterate through nested levels of columns containing data.tables, but the javascript necessary to do this is beyond me..

[mtcars_nested.R.txt](https://github.com/rstudio/shiny-examples/files/926839/mtcars_nested.R.txt)

**Comment by davlee1972** [comment]
Took another stab at this today.. Got some partial successes with formatting child rows as another nested datatable, but for some reason only the first set of child rows is being formatted.

[mtcars_nested_datatable.R.txt](https://github.com/rstudio/shiny-examples/files/930953/mtcars_nested_datatable.R.txt)

**Comment by davlee1972** [comment]
Ok got this working.. Took mtcars and grouped it by mpg and cyl to create a data table. If you click on the + icon the child rows for the cars show up as another nested data table.

[mtcars_nested_datatable.R.txt](https://github.com/rstudio/shiny-examples/files/931386/mtcars_nested_datatable.R.txt)

**Comment by davlee1972** [comment]
More complex example with multiple levels of nesting.. This assumes the first column of every nested table is a detail-control class (+) and the last column is the next level of nested data.

    datatable(
      data = my_data_dt,
      escape = -1,
      extensions = c('FixedHeader', 'Buttons', 'ColReorder', 'Scroller'),
      options = list(
        dom = 'Bfrti',
        autoWidth = FALSE,
        colReorder = TRUE,
        deferRender = TRUE,
        scrollX = TRUE,
        scrollY = "51vh",
        scroller = TRUE,
        scollCollapse = TRUE,
        fixedHeader = TRUE,
        buttons = c(I('colvis'), 'copy', 'csv', 'excel', 'pdf', 'print'),
        columnDefs = list(
          list(orderable = FALSE, className = 'details-control', targets = 0)
        )
      ),
      callback = JS("
    table.column(1).nodes().to$().css({cursor: 'pointer'});

    // Format child object into another table
    var format = function(d) {
      if(d != null){ 
        var result = '<table id=\"' + d[1] + '\"><thead><tr>'
        for (var col in d[d.length - 1][0]){
          result += '<th>' + col + '</th>'
        }
        result += '</tr></thead></table>'
        return result
      }else{
        return '';
      }
    }

    var format_datatable = function(d) {
      if(d != null){ 
        var subtable = $('table#' + d[1]).DataTable({
          'data': d[d.length - 1].map(Object.values),
          'autoWidth': false, 
          'deferRender': true, 
          'info': false, 
          'lengthChange': false, 
          'ordering': false, 
          'paging': false, 
          'scrollX': false, 
          'scrollY': false, 
          'searching': false ,
          'columnDefs': [{'orderable': false, 'className': 'details-control', 'targets': 0}]
        });
      }
    };

    table.on('click', 'td.details-control', function() {
      var table = $(this).closest('table');
      var td = $(this)
      var row = $(table).DataTable().row(td.closest('tr'));
      if (row.child.isShown()) {
        row.child.hide();
        td.html('&oplus;');
      } else {
        row.child(format(row.data())).show();
        td.html('&CircleMinus;');
        format_datatable(row.data())
      }
    });

    ")
      )
    })

**Comment by bogdanrau** [comment]
@davlee1972 Can you post the code to get my_data_dt in your 'more complex' example? I've been trying to wrap my head around it for over an hour and can't seem to get that example to run. Thanks for your examples!

**Comment by davlee1972** [comment]
Here's an updated version, but it isn't perfect..
Need to somehow detect which child tables are the last node in the tree
Need to come up with better unique table id instead of relying on the first column value in a table.

`
library(data.table)
library(DT)
library(shiny)

ui <- fluidPage(fluidRow(DT::dataTableOutput(width = "100%", "table")))

server <- function(input, output) {

output$table = DT::renderDataTable({

    mtcars_dt = data.table(mtcars)
    setkey(mtcars_dt,mpg,cyl)
    mpg_dt = unique(mtcars_dt[, list(mpg, cyl)])
    setkey(mpg_dt, mpg, cyl)
    cyl_dt = unique(mtcars_dt[, list(cyl)])
    setkey(cyl_dt, cyl)

    mtcars_dt = mtcars_dt[,list(mtcars=list(.SD)), by = list(mpg,cyl)]
    mtcars_dt[, ' ' := '&#9658;']

    mpg_dt = merge(mpg_dt,mtcars_dt, all.x = TRUE )
    setkey(mpg_dt, cyl)
    setcolorder(mpg_dt, c(length(mpg_dt),c(1:(length(mpg_dt) - 1))))

    mpg_dt = mpg_dt[,list(mpg=list(.SD)), by = cyl]
    mpg_dt[, ' ' := '&#9658;']

    cyl_dt = merge(cyl_dt,mpg_dt, all.x = TRUE )
    setcolorder(cyl_dt, c(length(cyl_dt),c(1:(length(cyl_dt) - 1))))

    DT::datatable(
      data = cyl_dt,
      rownames = FALSE,
      escape = -1,
      extensions = c('Scroller'),
      options = list(
        dom = 'Bfrti',
        autoWidth = TRUE,
        stripeClasses = list(),
        deferRender = TRUE,
        scrollX = TRUE,
        scrollY = "51vh",
        scroller = TRUE,
        scollCollapse = TRUE,
        columnDefs = list(
          list(orderable = FALSE, className = 'details-control', targets = 0),
          list(visible = FALSE, targets = -1 )
        )
      ),
      callback = JS("
    table.column(1).nodes().to$().css({cursor: 'pointer'})

    // Format child object into another table
    var format = function(d) {
      if(d != null){ 
        var result = ('<table id=\"' + d[1] + '\"><thead><tr>').replace('.','_')
        for (var col in d[d.length - 1][0]){
          result += '<th>' + col + '</th>'
        }
        result += '</tr></thead></table>'
        return result
      }else{
        return ''
      }
    }

    var format_datatable = function(d) {
      if(d != null){
        if ('SOME CHECK' == 'LAST SET OF CHILD TABLES') {
          var subtable = $(('table#' + d[1]).replace('.','_')).DataTable({
            'data': d[d.length - 1].map(Object.values),
            'autoWidth': false, 
            'deferRender': true, 
            'stripeClasses': [],
            'info': false, 
            'lengthChange': false, 
            'ordering': false, 
            'paging': false, 
            'scrollX': false, 
            'scrollY': false, 
            'searching': false 
          }).draw()
        }else{
          var subtable = $(('table#' + d[1]).replace('.','_')).DataTable({
            'data': d[d.length - 1].map(Object.values),
            'autoWidth': false, 
            'deferRender': true,
            'stripeClasses': [],
            'info': false, 
            'lengthChange': false, 
            'ordering': false, 
            'paging': false, 
            'scrollX': false, 
            'scrollY': false, 
            'searching': false,
            'columnDefs': [{'orderable': false, 'className': 'details-control', 'targets': 0},
            {'visible': false, 'targets': -1}]
          }).draw()
        }
      }
    }

    table.on('click', 'td.details-control', function() {
      var table = $(this).closest('table')
      var td = $(this)
      var row = $(table).DataTable().row(td.closest('tr'))
      if (row.child.isShown()) {
        row.child.hide()
        td.html('&#9658;')
      } else {
        row.child(format(row.data())).show()
        format_datatable(row.data())
        td.html('&#9660;')
      }
    })

    ")
      )
})
}

shinyApp (ui = ui, server = server)
`

**Comment by stanstrup** [comment]
Hi,

I have taken the fantastic example from @davlee1972's mtcars_nested_datatable.R.txt and changed the table manipulation to dplyr/tidyr style and I have generalized the call back so that it is now plug'n'play for nested tables.

Now my question is if it would be possible to get multiple layers of nesting for this example?


```r
library(DT)
library(tidyr)
library(dplyr)
library(tibble)

# nested data
mtcars_dt <- mtcars %>% 
                        rownames_to_column("model") %>% 
                        as_data_frame %>% 
                        select(mpg, cyl, model, everything()) %>% 
                        nest(-mpg, -cyl)


# add control column
data <- mtcars_dt %>% {bind_cols(data_frame(' ' = rep('&oplus;',nrow(.))),.)}

# get dynamic info and strings
nested_columns         <- which(sapply(data,class)=="list") %>% setNames(NULL)
not_nested_columns     <- which(!(seq_along(data) %in% c(1,nested_columns)))
not_nested_columns_str <- not_nested_columns %>% paste(collapse="] + '_' + d[") %>% paste0("d[",.,"]")

# The callback
# turn rows into child rows and remove from parent
callback <- paste0("
                    table.column(1).nodes().to$().css({cursor: 'pointer'});
                
                    // Format data object (the nested table) into another table
                    var format = function(d) {
                      if(d != null){ 
                        var result = ('<table id=\"child_' + ",not_nested_columns_str," + '\">').replace('.','_') + '<thead><tr>'
                        for (var col in d[",nested_columns,"]){
                          result += '<th>' + col + '</th>'
                        }
                        result += '</tr></thead></table>'
                        return result
                      }else{
                        return '';
                      }
                    }
                
                    var format_datatable = function(d) {
                      var dataset = [];
                      for (i = 0; i < + d[",nested_columns,"]['model'].length; i++) {
                        var datarow = [];
                        for (var col in d[",nested_columns,"]){
                          datarow.push(d[",nested_columns,"][col][i])
                        }
                        dataset.push(datarow)
                      }
                      var subtable = $(('table#child_' + ",not_nested_columns_str,").replace('.','_')).DataTable({
                        'data': dataset,
                        'autoWidth': true, 
                        'deferRender': true, 
                        'info': false, 
                        'lengthChange': false, 
                        'ordering': true, 
                        'paging': false, 
                        'scrollX': false, 
                        'scrollY': false, 
                        'searching': false 
                      });
                    };
                
                    table.on('click', 'td.details-control', function() {
                      var td = $(this), row = table.row(td.closest('tr'));
                      if (row.child.isShown()) {
                        row.child.hide();
                        td.html('&oplus;');
                      } else {
                        row.child(format(row.data())).show();
                        td.html('&CircleMinus;');
                        format_datatable(row.data())
                      }
                    });"
                  )


datatable(
  data,
  escape = -2, # raw HTML in column 2
  options = list(
                  columnDefs = list(
                                    list(visible = FALSE, targets = c(0,nested_columns) ), # Hide row numbers and nested columns
                                    list(orderable = FALSE, className = 'details-control', targets = 1) # turn first column into control column
                                    )
                ),
  callback = JS(callback)
)
```

**Comment by stanstrup** [comment]
This breaks if a nested table also contains a nested table. No data is shown for such a row. Any ideas?

**Comment by davlee1972** [comment]
Did you convert the version in the mtcars_nested_datatable.R.txt or the latest version I posted from June 17th?

The posted version from June 17th supports multiple levels of nesting assuming the last column of each row contains a nested table. If the cell of data is NULL (aka doesn't contain a nested table) then it doesn't render a arrow icon nor tries to format data into another nested table..

                    **if(d != null){** 
                    var result = ('<table id=\"' + d[1] + '\"><thead><tr>').replace('.','_')
                    for (var col in d[d.length - 1][0]){
                    result += '<th>' + col + '</th>'
                    }
                    result += '</tr></thead></table>'
                    return result
                    }else{
                    **return ''**
                    }
                    }

**Comment by stanstrup** [comment]
I took the first version. On my computer the 2nd version seems to have the same issue I am experiencing with the data you posted. The data is never shown for the nested table:
![image](https://user-images.githubusercontent.com/4532682/31248023-aee6ebc4-aa12-11e7-8328-307c6f4285ee.png)
I wonder if something was changed since then that could have broken it.

**Comment by davlee1972** [comment]
Run it in Chrome.

**Comment by stanstrup** [comment]
Oh maaan :grimacing: That worked... Thanks.

I don't think that particular layout will work nicely for my use-case in the end though. So I set up a question on SO for where I am currently stuck: https://stackoverflow.com/questions/46593607/datatable-with-nesting-child-rows-and-modal 
The Java scripting is surpassing my hacking skills...

**Comment by davlee1972** [comment]
You can inject formatting for every single table depending on how you want it to look.. Floating headers, justification, etc..
https://rstudio.github.io/DT/
https://datatables.net/

I think these are my usual suspects for formatting..

      extensions = c('FixedHeader', 'Buttons', 'ColReorder', 'Scroller'),
      options = list(
        dom = 'Bfrti',
        stripeClasses = list(),
        autoWidth = TRUE,
        colReorder = TRUE,
        deferRender = TRUE,
        scrollX = TRUE,
        scrollY = "51vh",
        scroller = TRUE,
        scollCollapse = TRUE,

**Comment by stanstrup** [comment]
Thanks again. I used your last example now and I think I more or less understand. It is working as designed.

Is there an easy way to set a maximum number of sub-grouping? So that for my use-case I can limit it to one layer of grouping and the have another layer of nesting I want to look at using a modal.

**Comment by stanstrup** [comment]
OK I managed to get the one level of grouping only by remove the lines in the java script.

```
 // 'columnDefs': [{'orderable': false, 'className': 'details-control', 'targets': 0},
 // {'visible': false, 'targets': -1}]
```

**Comment by gryslik** [comment]
Hi,

Is there a way to get this to work with the 'FixedColumns' extensions? I find that when I do that the row ordering breaks if I look at it in the browser and it stops working if I do it just in R.

Observe the following for a full example:

```
library(DT)
temp <- datatable(
  escape = -2,
  cbind(' ' = '&oplus;', mtcars),
  extensions = c('FixedColumns'),
  options = list(
    columnDefs = list(
      list(visible = FALSE, targets = c(0, 2, 3)),
      list(orderable = FALSE, className = 'details-control', targets = 1)
    ),
    dom ='Bfrtip',
    fixedColumns = list(leftColumns = 3, rightColumns = 0),
    pageLength = 1000, scrollX = TRUE,
    deferRender = TRUE,
    scrollY = "250px",
    scroller = TRUE
  ),
  callback = JS("
                table.column(1).nodes().to$().css({cursor: 'pointer'});
                var format = function(d) {
                return '<div style=\"background-color:#eee; padding: .5em;\"> Model: ' +
                d[0] + ', mpg: ' + d[2] + ', cyl: ' + d[3] + '</div>';
                };
                table.on('click', 'td.details-control', function() {
                var td = $(this), row = table.row(td.closest('tr'));
                if (row.child.isShown()) {
                row.child.hide();
                td.html('&oplus;');
                } else {
                row.child(format(row.data())).show();
                td.html('&CircleMinus;');
                }
                });"
))
```

**Comment by Plum57** [comment]
davelee1972, 

Just came across this and I've not been able to get your example from june 17th to work.  When I launch it, the table immediately fails with the error: "DataTables warning: table id = DataTables_Table_0 - Error in `[<-.data.frame`(`*tmp*`,,j,value = list(structure(list(' ' = c("&#9658;",: replacement element 1 is a matrix/data frame of 9 rows, need 3. "

I'm not sure what what is causing the error.

**Comment by davlee1972** [comment]
I just copied and pasted the June 17th code into my rstudio and ran it. It still works in a chrome browser..

Running R version 3.3.3
data.table version 1.10.4
dplyr version 0.5.0

**Comment by Plum57** [comment]
What version of DT are you using? 

my versions are:
R 3.4.3
DT 0.4
dplyr 0.7.4
data.table 1.10.4-3

**Comment by davlee1972** [comment]
R 3.3.3 on my PC
DT 0.2
dplyr 0.5.0
data.table 1.10.4

I get the same error after upgrading just packages to the latest version. Not sure if i have time to debug this this week..

If I look at cyl_dt and cyl_dt[1]$mpg it has:
> cyl_dt
           cyl          mpg
1: &#9658;   4 <data.table>
2: &#9658;   6 <data.table>
3: &#9658;   8 <data.table>

> cyl_dt[1]$mpg
[[1]]
            mpg       mtcars
1: &#9658; 21.4 <data.table>
2: &#9658; 21.5 <data.table>
3: &#9658; 22.8 <data.table>
4: &#9658; 24.4 <data.table>
5: &#9658; 26.0 <data.table>
6: &#9658; 27.3 <data.table>
7: &#9658; 30.4 <data.table>
8: &#9658; 32.4 <data.table>
9: &#9658; 33.9 <data.table>

This should be correct.. Clicking on the first row should produce a child data table with nine records. It looks like it is somehow iterating through the data structure and maybe trying to add extra columns to the parent table of 3 records from the child record of 9 rows.

**Comment by Plum57** [comment]
Thanks Dave.  I'll be working on it some myself.  I will let you know if I solve it.

**Comment by davlee1972** [comment]
Here's a partial fix. with two outstanding issues.

1. Can't get the HTML arrows to show up. Must be something simple I'm missing.
2. Headers and Columns aren't aligning.

I ended up getting rid of all the nested data tables and converted everything to JSON strings and then used Javascript to convert JSON strings into Objects.

library(data.table)
library(DT)
library(shiny)
library(jsonlite)

ui <- fluidPage(fluidRow(DT::dataTableOutput(width = "100%", "table")))

server <- function(input, output) {

output$table = DT::renderDataTable({

mtcars_dt = data.table(mtcars)
setkey(mtcars_dt,mpg,cyl)
mpg_dt = unique(mtcars_dt[, list(mpg, cyl)])
setkey(mpg_dt, mpg, cyl)
cyl_dt = unique(mtcars_dt[, list(cyl)])
setkey(cyl_dt, cyl)

mtcars_dt = mtcars_dt[, toJSON(.SD), by = list(mpg,cyl)]
setnames(mtcars_dt,'V1','mtcars')
mtcars_dt[, ' ' := '&#9658;']

mpg_dt = merge(mpg_dt,mtcars_dt, all.x = TRUE )
setkey(mpg_dt, cyl)
setcolorder(mpg_dt, c(length(mpg_dt),c(1:(length(mpg_dt) - 1))))

mpg_dt = mpg_dt[, toJSON(.SD), by = cyl]
setnames(mpg_dt,'V1','mpg')
mpg_dt[, ' ' := '&#9658;']

cyl_dt = merge(cyl_dt,mpg_dt, all.x = TRUE )
setcolorder(cyl_dt, c(length(cyl_dt),c(1:(length(cyl_dt) - 1))))

DT::datatable(
  data = cyl_dt,
  rownames = FALSE,
  escape = -1,
  options = list(
    dom = 'Bfrti',
    autoWidth = TRUE,
    stripeClasses = list(),
    deferRender = TRUE,
    scrollX = TRUE,
    scrollY = "51vh",
    scroller = TRUE,
    scollCollapse = TRUE,
    columnDefs = list(
      list(orderable = FALSE, className = 'details-control', targets = 0),
      list(visible = FALSE, targets = -1 )
    )
  ),
  callback = JS("
table.column(01).nodes().to$().css({cursor: 'pointer'})

var table_id = 1000

// Format child object into another table
var format = function(table_id, columns) {
  if(columns != null){ 
    var result = ('<table id=\"' + table_id + '\"><thead><tr>')
    for (var i in columns){
      result += '<th>' + columns[i] + '</th>'
    }
    result += '</tr></thead></table>'
    return result
  }else{
    return ''
  }
}

var format_datatable = function( table_id, newtable) {
  if(newtable != null){

    var column_defs = []
    var keys = Object.keys(newtable[0])

    for (var i in keys)
    {
      if (i == 0)
      {
        column_defs[i] = {'data': keys[i], 'name': keys[i], 'targets': parseInt(i), 'orderable': false, 'className': 'details-control'}
      }
      else if (i == keys.length - 1)
      {
        column_defs[i] = {'data': keys[i], 'name': keys[i], 'targets': parseInt(i), 'visible': false}
      }
      else
      {
        column_defs[i] = {'data': keys[i], 'name': keys[i], 'targets': parseInt(i)}
      }
    }


/*    alert(JSON.stringify(column_defs)) */

    if ('SOME CHECK' == 'LAST SET OF CHILD TABLES') {
      var subtable = $(('table#' + row_data[1])).DataTable({
        'data': newtable,
        'autoWidth': false, 
        'deferRender': true,
        'stripeClasses': [],
        'info': false, 
        'lengthChange': false, 
        'ordering': false, 
        'paging': false, 
        'scrollX': false, 
        'scrollY': false, 
        'searching': false,
        'columnDefs': [{'orderable': false, 'className': 'details-control', 'targets': 0},{'visible': false, 'targets': -1}]
      }).draw()
    }else{
      var subtable = $(('table#' + table_id).replace('.','_')).DataTable({
        'data': newtable,
        'autoWidth': false, 
        'deferRender': true,
        'stripeClasses': [],
        'info': false, 
        'lengthChange': false, 
        'ordering': false, 
        'paging': false, 
        'scrollX': false, 
        'scrollY': false, 
        'searching': false,
        'columnDefs': column_defs
      }).draw()
    }
  }
}


table.on('click', 'td.details-control', function() {
  var td = $(this)
  var table = $(td).closest('table')
  var row = $(table).DataTable().row(td.closest('tr'))

  if (row.child.isShown()) {
    row.child.hide()
    td.html('&#9658;')
  }
  else
  {
    var row_data = row.data()

    if (!Array.isArray(row_data))
    {

      row_data = Object.keys(row_data).map(function (key) {
        return row_data[key]
      });
    }

    var newtable = JSON.parse(row_data[row_data.length - 1])
    var columns = Object.keys(newtable[0])

    table_id++

    row.child(format(table_id, columns)).show()
    format_datatable(table_id, newtable)
    td.html('&#9660;')
  }

})


")
  )
})
}

shinyApp (ui = ui, server = server)

**Comment by amjadtalib** [comment]
@davlee1972 @Plum57 
As someone who's spent the better part of the past 48 hours pouring over R/Shiny code looking for an problem that wasn't there, I wish more than anything that I had rechecked this thread first.. 

I had to roll back to DT 0.2 to get my app working again. I'm not sure what exactly broke the package, but my hunch is it may have to do with a change to the actual DataTables js itself. As evidenced in this screenshot, they seem to have changed their site and featured our culprit functionality on the homepage...
![datatables net](https://user-images.githubusercontent.com/18545517/37495998-0e29a6b4-287e-11e8-993c-44266ff58295.jpeg)
 
If this bug is resolved or there's a workaround without having to convert everything to json first, please share!

**Comment by mahakgulati** [comment]
@stanstrup I tried implementing your solution posted on Oct 5, 2018. It ran successfully on my local machine but the childrows are not visible when I  run the same in Rstudio server. Can anyone please help me out.

**Comment by joelnc** [comment]
This may be an easy one for some on this thread (apparently not me).  

Making a very simple modification of @stanstrup's 2018-10-5 example (built off of @davlee1972's previous example), I tried adding an additional grouping variable using `disp`.  

```# nested data
mtcars_dt <- mtcars %>% 
                        rownames_to_column("model") %>% 
                        as_data_frame %>% 
                        select(mpg, cyl, model, disp, everything()) %>% 
                        nest(-mpg, -cyl, -disp)
```
This works partially, creating a 31 row nested table.  There is a two row child table for mpg/cyc/disp 21/6/160 (the only duplicate in this grouping), and several 1 row child tables as needed.   But for 12 of the rows where there would be only one row in the child table, child tables are just headers with no data.  Anyone see the problem?

**Comment by piyuw** [comment]
@joelnc yes i have a smilar issue, 

Ive used @davlee1972  example and substituted my own data to get a grouping of a few columns 

The resulting picture below is the output, but as you can see AccountRefFullname column and fullamount column only has the headers. 

in the case of the COGS row, its even missing the fullamount column heading.

These AccountRefFullname column and fullamount headings for the different financial  categories (should have multiple should have multiple rows underneath them. 


![image](https://user-images.githubusercontent.com/24651689/42945966-68874f8c-8b87-11e8-9441-17be55f24da4.png)


i dont have much of a javascript background and was hoping if anyone might be able to help out.

thanks 
piyuw

**Comment by stla** [comment]
@piyuw 's question is answered here: <https://stackoverflow.com/a/56599838/1100107>
