### ISSUE TITLE
Dashboard to summarize text data using RShiny

### ISSUE THREAD

**Issue by KafeelBasha** [rstudio/shiny-examples#91]
Hello
I have "feedback" data in text format, I would like to create a RShiny dashboard to summarize number of positive and negative feedback with a bar chart to represent its proportion. Tried with below codes, I am getting only the bar chart but not the count of different feedback in a value box, also the skin of the dashboard

please help me with this.
ui <- fluidPage(
 titlePanel("Feedback Summary"),
        sidebarPanel(
        selectInput("var",label="Choose a variable",choice=names(data), selectize=FALSE,selected=names(data)[11])),
      
      mainPanel(
      plotOutput("bar")
      ))

server<- function(input,output){
  demo=Corpus(VectorSource(data[,11]))
  demo=tm_map(demo,content_transformer(tolower))
  demo=tm_map(demo,removePunctuation)
  df<- data.frame(text=unlist(sapply(demo,`[`)),stringsAsFactors=F)
  df$text=ifelse(df$text=="poor"|df$text=="fair","BAD","GOOD")
  df%>%group_by(text)%>%summarise(count=n(),percentage=count/nrow(df))%>%as.data.frame()->stats
  rownames(stats)<-stats$text
  
  output$value1 <- renderValueBox({ 
    valueBox(
      formatC(stats$count[1], format="d", big.mark=',')
      ,'Number of Bad feedback'
      ,icon = icon("gbp",lib='glyphicon')
      ,color = "green")  
  })
  output$value2 <- renderValueBox({ 
    valueBox(
      formatC(stats$count[2], format="d", big.mark=',')
      ,'Number of Good feedback'
      ,icon = icon("gbp",lib='glyphicon')
      ,color = "green")  
  })
  
  output$bar <- renderPlot({
    ggplot(stats,aes(x=stats$text,y=stats$percentage,fill=text))+geom_bar(stat="identity")+geom_text(label=stats$percentage,vjust=-0.5)
  })}

shinyApp(ui, server)

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

**Comment by KafeelBasha** [comment]
I have created a script for ui as ui.R and for server as server.R, now I am getting below error
![image](https://user-images.githubusercontent.com/22866208/41920418-4f0af196-797e-11e8-98cf-383a18312122.png)

**Comment by KafeelBasha** [comment]
Thanks
